# fly.toml app configuration file generated for kwahooligan-capi on 2023-10-19T22:29:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kwahooligan-capi"
primary_region = "lhr"

[build]

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stdout"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  REDIRECT_URI = "SECRET"
  WAHOO_CLIENT_ID = "SECRET"
  WAHOO_CLIENT_SECRET = "SECRET"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
